name: Deploy to Azure (Container Apps + Dapr)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  AZD_ENV: dev
  AZD_LOCATION: eastus

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install Azure Dev CLI
        uses: Azure/setup-azd@v1

      - name: Initialize azd env
        run: |
          azd env set AZURE_SUBSCRIPTION_ID ${{ secrets.AZURE_SUBSCRIPTION_ID }} || true
          azd env set AZURE_TENANT_ID ${{ secrets.AZURE_TENANT_ID }} || true
          azd env set AZURE_CLIENT_ID ${{ secrets.AZURE_CLIENT_ID }} || true
          azd env new $AZD_ENV --location $AZD_LOCATION --no-prompt || azd env select $AZD_ENV

      - name: Deploy
        run: azd up --no-prompt --environment $AZD_ENV --location $AZD_LOCATION

      - name: Show Endpoints
        run: azd env get-values | grep -E 'productserviceUrl|orderserviceUrl' || true
